#define SCREEN_WIDTH 640.0f
#define SCREEN_HEIGHT 480.0f
#define WORLD_WIDTH 80.0f
#define WORLD_HEIGHT 60.0f

#define SCROLL_WIDTH_LEFT 180.0f
#define SCROLL_WIDTH_RIGHT 540.0f


#define WANDER 0
#define STALL 1
#define SEEK 2
#define ATTACK 3
#define FLEE 4
#define STOP 5

enum { HIT=0, FRONT_KICK=1, TORNADO_KICK = 3, SPINNING_BACK_KICK = 2, WALK = 5, RUN = 4, LINE_BUFF_SIZE = 128, FPS=30, PLAYER=0, ENEMY=1, PLAYER_LEFT=1, PLAYER_RIGHT=2, PLAYER_UP=4, PLAYER_DOWN=8};
