#define SCREEN_WIDTH 800.0f
#define SCREEN_HEIGHT 600.0f
#define WORLD_WIDTH 80.0f
#define WORLD_HEIGHT 60.0f

#define WANDER 0
#define STALL 1
#define SEEK 2
#define ATTACK 3
#define FLEE 4

enum { HIT=0, FRONT_KICK=1, TORNADO_KICK = 3, SPINNING_BACK_KICK = 2, WALK = 5, RUN = 4, LINE_BUFF_SIZE = 128, FPS=30, PLAYER=0, ENEMY=1, PLAYER_LEFT=1, PLAYER_RIGHT=2, PLAYER_UP=4, PLAYER_DOWN=8};
